namespace RetroDrive.Api.Contracts;

public sealed record AdminVehicleResponse(
    long Id,
    bool Published,
    DateTimeOffset CreatedAt,
    string Slug,
    int Year,
    string Make,
    string Model,
    decimal Price,
    string? PriceText,
    decimal? Msrp,
    int Mileage,
    string Vin,
    string ExteriorColor,
    string InteriorColor,
    string Engine,
    string Horsepower,
    string Transmission,
    string BodyStyle,
    string Location,
    string StockNumber,
    string Description,
    IReadOnlyList<string> Features,
    IReadOnlyList<string> PhotoPublicIds,
    IReadOnlyList<string> ImageUrls);
